const roundCards = [

    {
        name: "100",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/rustig.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel iets waar je rustig van wordt.",
        category: "1",
        player: "0",

    },
]

const allCards = [


    {
        name: "0",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/rustig.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel iets waar je rustig van wordt.",
        category: "1",
        player: "0",

    },
    {
        name: "1",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/bang.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je bang maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "2",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/blij.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je blij maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "3",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/boos.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je boos maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "4",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/eenzaam.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je eenzaam maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "5",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/gefrustreerd.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je gefrustreerd maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "6",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/gemotiveerd.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je gemotiveerd maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "7",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/onrustig.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je onrustig maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "8",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/onzeker.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je onzeker maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "9",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/teleurgesteld.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je teleurgesteld maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "10",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/verdrietig.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat je verdrietig maakte.",
        category: "1",
        player: "0",

    },
    {
        name: "11",
        colorDark: "#FAB234",
        colorLight: "#FDD791",
        categoryName: "Emotie",
        imageFront: "./images/emoties/voldaan.png",
        imageBack: "./images/emotieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets waar je een voldaan gevoel bij kreeg.",
        category: "1",
        player: "0",

    },
    {
        name: "12",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef 1 tot 3 positieve vaardigheden over jezelf.",
        category: "2",
        player: "0",

    },
    {
        name: "13",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef 1 tot 3 verbeterpunten over jezelf.",
        category: "2",
        player: "0",

    },
    {
        name: "14",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Leg uit waarom vandaag beter of slechter is dan gisteren.",
        category: "2",
        player: "0",

    },
    {
        name: "15",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Neem een punt waarvan jezelf denkt dat je kan verbeteren en overtuig de ander dat het een pluspunt is.",
        category: "2",
        player: "0",

    },
    {
        name: "16",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Praat over een vaardigheid waar je goed in bent.",
        category: "2",
        player: "0",

    },
    {
        name: "17",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Praat over een vaardigheid waar je beter in wil worden.",
        category: "2",
        player: "0",

    },
    {
        name: "18",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Praat over iets waar je naar uitkijkt.",
        category: "2",
        player: "0",

    },
    {
        name: "19",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Praat over iets waar je niet naar uitkijkt.",
        category: "2",
        player: "0",

    },
    {
        name: "20",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat niet zo goed ging, maar waar je nu wel om kan lachen.",
        category: "2",
        player: "0",

    },
    {
        name: "21",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over iets wat veel beter ging dan je had verwacht.",
        category: "2",
        player: "0",

    },
    {
        name: "22",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over je grootste minpunt van gisteren.",
        category: "2",
        player: "0",

    },
    {
        name: "23",
        colorDark: "#66CCCE",
        colorLight: "#B3E6E4",
        categoryName: "Reflectie",
        imageFront: "./images/reflectieIcon.png",
        imageBack: "./images/reflectieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel over je grootste pluspunt van gisteren.",
        category: "2",
        player: "0",

    },
    {
        name: "24",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef 1 tot 3 positieve eigenschappen die jullie gemeen hebben.",
        category: "3",
        player: "0",

    },
    {
        name: "25",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef 1 positieve eigenschap die zich verschillend uit tussen jullie twee.",
        category: "3",
        player: "0",

    },
    {
        name: "26",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef 1 tot 3 redenen waarom je de ander waardeert.",
        category: "3",
        player: "0",

    },
    {
        name: "27",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef een compliment over zijn/ haar eigenschappen.",
        category: "3",
        player: "0",

    },
    {
        name: "28",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef een compliment over zijn/ haar persoonlijkheid.",
        category: "3",
        player: "0",

    },
    {
        name: "29",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef een compliment over zijn/ haar prestaties.",
        category: "3",
        player: "0",

    },
    {
        name: "30",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef een compliment over zijn/ haar uiterlijk.",
        category: "3",
        player: "0",

    },
    {
        name: "31",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Geef een compliment over zijn/ haar vaardigheden.",
        category: "3",
        player: "0",

    },
    {
        name: "32",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel de ander over iets waar je trots op bent.",
        category: "3",
        player: "0",

    },
    {
        name: "33",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Vertel de ander wat je graag samen zou willen doen.",
        category: "3",
        player: "0",

    },
    {
        name: "34",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Vraag de ander om advies over iets wat je vervelend of onduidelijk vind.",
        category: "3",
        player: "0",

    },
    {
        name: "35",
        colorDark: "#F573C0",
        colorLight: "#FAB9E0",
        categoryName: "Connectie",
        imageFront: "./images/connectieIcon.png",
        imageBack: "./images/connectieIcon.png",
        backgroundShape: "./",
        textContent: "Vraag de ander om hulp met iets wat je wilt/ gaat doen.",
        category: "3",
        player: "0",

    },
    {
        name: "36",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over een boek, film, serie, video game of ander creatief werk.",
        category: "4",
        player: "0",

    },
    {
        name: "37",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over een concert, optreden of ander evenement.",
        category: "4",
        player: "0",

    },
    {
        name: "38",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over familie.",
        category: "4",
        player: "0",

    },
    {
        name: "39",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over het nieuws.",
        category: "4",
        player: "0",

    },
    {
        name: "40",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over het weer.",
        category: "4",
        player: "0",

    },
    {
        name: "41",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Vraag naar de ander zijn/ haar weekend.",
        category: "4",
        player: "0",

    },
    {
        name: "42",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over iets wat je gegeten hebt of iets wat je graag lust.",
        category: "4",
        player: "0",

    },
    {
        name: "43",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over sport en fysieke activiteiten.",
        category: "4",
        player: "0",

    },
    {
        name: "44",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over waar je op vakantie bent geweest of zou willen gaan.",
        category: "4",
        player: "0",

    },
    {
        name: "45",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Praat over werk, opleiding of professioneel leven.",
        category: "4",
        player: "0",

    },
    {
        name: "46",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Vertel iets grappigs of laat iets grappigs zien.",
        category: "4",
        player: "0",

    },
    {
        name: "47",
        colorDark: "#73CB5E",
        colorLight: "#B9E5A5",
        categoryName: "Smalltalk",
        imageFront: "./images/smalltalkIcon.png",
        imageBack: "./images/smalltalkIcon.png",
        backgroundShape: "./",
        textContent: "Vertel iets over je huisdier of een ander dier als je geen huisdieren hebt.",
        category: "4",
        player: "0",

    },





    // {
    //     name: "0",
    //     color: "#FAB234",
    //     content: "<p>this is card yellow 1</p>",
    //     backContent: "<p>this is the back of card yellow 1</p>",
    //     category: "1",
    //     player: "0",
    // },

]

export { allCards, roundCards }